### ISSUE TITLE
iOS 7

### ISSUE THREAD

**Issue by tujoworker** [McDo/tipop#1]
Hi McDo!

thanks for making this module! You are great!
I tested this with iOS 7 on both an device and the simulator.

I get an error and the app crashes immiditly without starting titanium related things.
Do you know about that already?

**Comment by tujoworker** [comment]
Does this mean something to someone?

> dyld: Symbol not found: __dealloc
>   Referenced from: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
>   Expected in: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.1.sdk/usr/lib/libobjc.A.dylib
>  in /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
> (lldb)

**Comment by yozef** [comment]
Honestly, I tried out this module with Ti.SDK 3.4.1 and works beautifully. Make sure the module is installed properly.

and try this out:

``` javascript
//load component dependencies
    var POP = require("guy.mcdooooo.tipop");

    //create component instance
    var self = Ti.UI.createWindow({
        backgroundColor:'#ffffff'
    });

    //construct UI
    var firstView = Ti.UI.createView({
        width: 200, height:100, backgroundColor:'red', bottom: 30, left: 20
    });
    firstView.addEventListener('click', function() {
        POP.basic(firstView, {
            top:100, 
            left:500,
            opacity: 0.7,
            backgroundColor: '#AABBE0', // to blue
            borderRadius:30,
            easing: 'easeOut',
        });
    });
    self.add(firstView);
```

**Comment by tujoworker** [comment]
Hi, thanks for your quick reply!

Yes, on iOS8 it works just fine for me as well. But not iOS7 - did you test it on iOS7?
You can download iOS7 Simulator in xcode as the screenshot shows you:

![skjermbilde 2015-01-09 kl 20 09 48](https://cloud.githubusercontent.com/assets/1501870/5685565/ade8f262-983b-11e4-8055-7a12c1cd3194.png)

**Comment by McDo** [comment]
hi @colorhat
working around this ios7 issue quite some time but didn't figure it out :-/ 
find some useful information related on [stackoverflow](http://stackoverflow.com/questions/26505658/ios-simulator-7-1-crash-running-on-yosemite-with-weak-linked-new-frameworks-sym)

> The [Xcode 6.1 Release Notes](https://developer.apple.com/library/ios/releasenotes/DeveloperTools/RN-Xcode/Chapters/xc6_release_notes.html) mention this issue:
> 
> If an app is weak linked against frameworks new in iOS 8 SDK and OS X 10.10 SDK, it may fail to run if the run destination is an iOS Simulator for older iOS runtimes and the host system is running OS X Yosemite. (17807439) 

For tipop, I doubted it's about to weak link the SceneKit.framework into the project, but not quite sure.
To be countinue...

**Comment by McDo** [comment]
Hi @colorhat 
I've fixed the crashing issue for ios7 simulator, plz check out the updated module. 
The bug is caused by importing ios8 SceneKit.framework into the ios7 building target. The original condition checking of FB POP defined in "POPDefines.h" that prevent importing SceneKit for the ios<8.0 is invalid in ios7 simulator.
BTW, I didn't have any ios7 device at hand to test, sorry about that (thought it should be work:-)

**Comment by tujoworker** [comment]
Hi McDo,

i tested the new version (1.0.1) on the simulator, and get this error. Looks for me as the same as before:

> dyld: Symbol not found: __dealloc
>   Referenced from: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
>   Expected in: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.1.sdk/usr/lib/libobjc.A.dylib
>  in /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
> (lldb)

**Comment by tujoworker** [comment]
Running it on a device with 7.1 I get this error:

> dyld: Library not loaded: /System/Library/Frameworks/SceneKit.framework/SceneKit

Looks like heres a solution? (The problem was setting the added frameworks as required instead of optional) http://stackoverflow.com/questions/12915050/still-dyld-library-not-loaded

**Comment by tujoworker** [comment]
I build the module on my machine and played a little but with it, and it looks like POP from facebook is not made for iOS. Right?

**Comment by McDo** [comment]
remove SceneKit support at the time, works for me... @colorhat plz try it out

**Comment by colorhat** [comment]
Works fine for me now on iOS7 simulator/device. Wonderfull.

**Comment by tujoworker** [comment]
Works fine for me now on iOS7 simulator/device. Wonderfull.
