### ISSUE TITLE
CAShapeLayer Animation example?

### ISSUE THREAD

**Issue by agrycroko** [McDo/tipop#11]
Hi,

Great module, been using it lots.

I want to create a circular countdown for my app without using bitmap images. Could the CAShapeLayer Animations do this?

This is the kind of thing I want to do:
[goo.gl/qJzoPC](https://goo.gl/qJzoPC)

Have you got any examples using arcs etc.?

Thanks.

**Comment by McDo** [comment]
Hi @garycrook ,
plz checkout the [Tibezier](https://github.com/McDo/Tibezier) module.

**Comment by agrycroko** [comment]
Wow, you are THE MAN!!

Thanks.
