### ISSUE TITLE
Samples and examples

### ISSUE THREAD

**Issue by nuno** [McDo/tipop#2]
Hello, thanks for this project, you have any demo app with some sample code examples by chance?

**Comment by yozef** [comment]
Here's an example:

```
//load component dependencies
var POP = require("guy.mcdooooo.tipop");

//create component instance
var self = Ti.UI.createWindow({
    backgroundColor:'#ffffff'
});

//construct UI
var firstView = Ti.UI.createView({
    width: 200, height:100, backgroundColor:'red', bottom: 30, left: 20
});
firstView.addEventListener('click', function() {
    // the magic
    POP.basic(firstView, {
            top:100, 
            left:500,
            opacity: 0.7,
            backgroundColor: '#AABBE0', // to blue
            borderRadius:30,
            easing: 'easeOut',
        });
});
self.add(firstView);

self.open();
```

**Comment by McDo** [comment]
Hi @nuno :
The usage is exactly the sample code @yozef showed, try different animations (basic, spring and decay) with their properties (easing, springBounciness or delay etc.) as the [Function List](https://github.com/McDo/tipop#2-function-list) described.

**Comment by McDo** [comment]
Hi @nuno :
The usage is exactly the sample code @yozef showed, try different animations (basic, spring and decay) with their properties (easing, springBounciness or delay etc.) as the Function List described.

**Comment by McDo** [comment]
Hi @nuno :
The usage is exactly the sample code @yozef showed, try different animations (basic, spring and decay) with their properties (easing, springBounciness or delay etc.) as the [Function List](https://github.com/McDo/tipop#2-function-list) described.

**Comment by nuno** [comment]
@yozef @McDo Cool, I will try right way :) Thanks
