### ISSUE TITLE
The standard way to access an instance to use other/different properties?

### ISSUE THREAD

**Issue by nuno** [McDo/tipop#3]
Hey, love this port, thank you for that again!

What is the better way to access an instance to use other/different properties?

ex:

```
_button.addEventListener('click', function tapMe (_evt) {
  _timerRunning = !_timerRunning;

var myinstance = POP.spring(_button, {
    springBounciness: 10.0,
    pringSpeed: 10.0
   });

if(_timerRunning){

    myinstance.width = 37,
    myinstance.height = 37,

}else{
    myinstance.width =  44,
    myinstance.height =  44,
}

 });
´´´

If I do this way I get errors, make since?
```

**Comment by nuno** [comment]
Sorry I think I figure out, what you think in terms of best practices?

``` javascript
var animationButton = {
  springBounciness: 20,
  pringSpeed: 10
}

if(_timerRunning){
  animationButton.width = 37;
  animationButton.height = 37;
}else{
  animationButton.width = 44;
  animationButton.height = 44;  
}

POP.spring(_button, animationButton);
```

**Comment by nuno** [comment]
@McDo I have some cool samples that I built with this module, I will open source it :)
sample popup: https://youtu.be/nXSncSc3IaI
Question: Is possible access to "complete" event when the animation completes, or sort of thing?

Or is better Titanium.UI.Animation event? Do you want share how do you handle that?

ex:

```
[positionAnimation setCompletionBlock:^(POPAnimation *anim, BOOL finished) {
        [transitionContext completeTransition:YES];
    }];
```

**Comment by McDo** [comment]
@nuno, didn't implement the completion callback at the time, sorry about that. plz consider to use  the setTimeout as the current workaround. gonna add this feature as soon as i got time.

**Comment by nuno** [comment]
@McDo Great, actually was what I did "setTimeout" 

Thank you.

Btw do you know this project http://facebook.github.io/rebound/ ?  kinda of pop for android :)

**Comment by McDo** [comment]
@nuno, i've heard about it but didn't give a try. should be cool if some guy integrate it into titanium.
