### ISSUE TITLE
iOS bug with "unfinished" animations using new callback

### ISSUE THREAD

**Issue by alvesl** [McDo/tipop#5]
Hello, first of all, thank you so much for this module, it's really great!
Also, thank you for implementing the new callback option, it really is very useful.

I ran into what looks like a bug when I tried to use it to animate transition between windows, something like:

  // Create closing animation
  POP.basic($.window, {
    left: Ti.Platform.displayCaps.platformWidth,
    duration: 350,
    easing: 'easeOutCubic'
  }, function() {
    $.window.close();
  });

I called the above method whenever a "back" button was pressed in my view.

This would work 9 out of 10 times, but sometimes, only sometimes, it looks like the animation never completes, and therefore the window is never closed... When that happens my layout instantly becomes unresponsive, and what's worse, the app does NOT crash, leaving the user to experience a "freeze-like" situation.

Is this a bug or am I doing something wrong? Calling POP on a Window element could be the problem?

Thanks in advance for any inputs!

**Comment by McDo** [comment]
Hi @alvesl ,
I cannot regenerate the issue with the code. Maybe put some Ti.API.info into the callback to see if the callback is not being called indeed.
Here is the code I use:

``` javascripts
var POP = require("guy.mcdooooo.tipop");

var btn = Ti.UI.createButton({
    title: "GO",
    width: 100,
    top: 80
});

var resetBtn = Ti.UI.createButton({
    title: "RESET",
    tintColor: "#FF3B30",
    width: 100,
    top: 50
});

function popping() {
        POP
    .basic($.window2, {
        left: 600,
        duration: 350,
        easing: 'easeOutCubic'
    }, function() {
        $.window2.close();
        Ti.API.info('hi');
    });
}

$.window.add( resetBtn );
$.window2.add( btn );
btn.addEventListener('click', popping);
resetBtn.addEventListener('click', function() {
        $.window2.open();
    $.window2.left = 0;
});

$.window.open();
$.window2.open();
```

Or send me the codebase and info of the devices you tested.

**Comment by alvesl** [comment]
Sorry, I have been away for a while. I will create a separate codebase for this and will get back to you.

As always, thank you for your time & awesome module.

**Comment by alvesl** [comment]
Hello,

I was able to reproduce the issue, though I needed to create a map on the second screen, and close it as soon as it opened.

the following code generates a crash:

```
var POP = require("guy.mcdooooo.tipop");

    var btn = Ti.UI.createButton({
        title: "GO",
        width: 100,
        top: 80
    });

    $.index.add(btn);

    var win2 = Ti.UI.createWindow({
      backgroundColor: 'green'
    });


    var resetBtn = Ti.UI.createButton({
        title: "RESET",
        tintColor: "#FF3B30",
        width: 100,
        top: 50
    });

    win2.add(resetBtn);

    var Map = require('ti.map');

      var mapview = Map.createView({
        height: '100%',
        top: 200,
        width: '100%',
        height: Ti.UI.FILL,
        zIndex: 100,
        mapType: Map.NORMAL_TYPE,
        region: {latitude:-22.925831, longitude:-43.176631,
                  latitudeDelta:0.01, longitudeDelta:0.01},
        regionFit:true,
        userLocation:true,
        enableZoomControls: false,
        compassEnabled: false,
        userLocationButton: true
      });

      win2.add(mapview);



    function popping() {
            POP
        .basic(win2, {
            left: 600,
            duration: 280,
            easing: 'easeOutCubic'
        }, function() {
            win2.close();
            Ti.API.info('hi');
        });
    }

    resetBtn.addEventListener('click', function(e) {
      popping();
    });

    btn.addEventListener("click", function(e) {
      win2.open();
    });

    $.index.open();
```

As you can see, I had to create a map on the second view and quickly close the window to generate the crash. The weird thing is that the callback was indeed fired:

```
[INFO] :   hi
[LiveView] Client disconnected
```

So now I'm wondering if this is an animation problem or a map problem. 
I thought the problem was the callback because changing the popping function to this fixes the problem:

```
function popping() {
        POP
    .basic($.window2, {
        left: 600,
        duration: 350,
        easing: 'easeOutCubic'
    });

_.delay(function() {
        win2.close();
        Ti.API.info('hi');
    }, 350);
}
```

*\* Crash occurs on the iOS simulator & also on the device.

**Comment by McDo** [comment]
hi @alvesl ,
Tested on your code, I thought the crashing was caused by quick load&unload the map view from your window. If I didn't  add mapview to the win2, everything worked fine. So maybe you could add a loader to give some breath time to the map loading and unloading, or just delay the window closing as you did. Basically, I don't think it's the problem of Tipop or POP. Hope it could help.

**Comment by alvesl** [comment]
Ok, thanks for looking into it! closing this now.
