### ISSUE TITLE
Titanium.Media.vibrate() not working inside of FBPOP callback

### ISSUE THREAD

**Issue by designbymind** [McDo/tipop#7]
Hi @McDo,

It seems as if the Titanium.Media.vibrate() throws an error if being executed inside of an FBPOP callback function. Any idea as to why this may be happening?

**Error message:**
[ERROR] : message = "undefined is not an object (evaluating 'Titanium.Media.vibrate')";

**Use case example:**
FBPOP.basic(myView, {
    scale : {
        x : .8,
        y : .8
    },
    duration : 300
}, function() {
    Titanium.Media.vibrate();
});

**P.S.** - I've been using this module everywhere & just want to say thanks!

· Jason

**Comment by McDo** [comment]
Hi @designbymind , it seems the callback does lose its execution context or something. I don't know. got drill down to the code for some time. come back later.

**Comment by designbymind** [comment]
Hi @McDo,

Thanks for your efforts & rapid reply!

I'll keep an active subscription to this issue thread.

😃

**Comment by kosso** [comment]
👍 +1

Callback is not firing for me either.

**Comment by McDo** [comment]
check out 1.0.6 plz

**Comment by designbymind** [comment]
@McDo · Works for me!

Tested against: Ti SDK 5.2.2.GA / iOS 9.3.1 (iPhone 6s & iPhone 6s Plus)

Thanks for the update 🙃

**Comment by McDo** [comment]
@designbymind awesome 😄
