### ISSUE TITLE
Is there a way to reset view position to its natural state?

### ISSUE THREAD

**Issue by mark22** [McDo/tipop#8]
I am using this amazing module to spin a circle around 360degrees to simulate a loading circle.   When my content is loaded I use the .clear method to stop the spinning, successfully.

However, the place the spinning stops is random, so my logo looks like its upside down, or at 90degrees or at some weird angle relative to its starting position.   (This is when using decay)

Is there any way to have it have everything go back to their normal original position/orientation?

Thanks!

**\* EDIT.  I see this is a more complicated issue related to the POP framework itself ( https://github.com/facebook/pop/issues/13 ).  SO I'm closing this now and otherwise thank you for this excellent module

**Comment by yozef** [comment]
yeah, since @McDo recently implemented the call back function, use that to set your spinner at the right angle.

**Comment by mark22** [comment]
@yozef But how to determine the correct angle?  It seems that all the angles are relative #s, so if i tell it to rotate to 360 its relative to where it is now (with a spinning circle that could be anywhere, so that when it stops its basically stopping somewhere randomly along the 360degrees
